### ISSUE TITLE
Can not import a simple FBX file contains 14 polygons

### ISSUE THREAD

**Issue by dszhblx** [godotengine/FBX2glTF#48] opened 2023-12-07 04:20 UTC
### Godot version

Godot 4.2, FBX2glTF 0.13.1

### System information

Windows 10

### Issue description

Can not import a simple FBX file contains 14 polygons.

### Steps to reproduce

[SM_Envr_Road_Road_03.zip](https://github.com/godotengine/FBX2glTF/files/13594923/SM_Envr_Road_Road_03.zip)
1.unzip SM_Envr_Road_Road_03.zip
2.put SM_Envr_Road_Road_03.fbx into a empty godot project

### Minimal reproduction project

[test-fbx.zip](https://github.com/godotengine/FBX2glTF/files/13594953/test-fbx.zip)

**Comment by dszhblx** [comment] 2023-12-07 07:15
the fbx file info:
![20231207151444](https://github.com/godotengine/FBX2glTF/assets/8831593/e80759fa-06f2-4098-bda1-073fa0410d69)

**Comment by fire** [comment] 2023-12-07 15:21
https://github.com/godotengine/godot/pull/81746 Can you also try this? Let me now if you need instruction how to download

**Comment by fire** [comment] 2023-12-08 12:54
Try https://nightly.link/V-Sekai/godot/workflows/runner/vsk-ufbx?preview

**Comment by dszhblx** [comment] 2023-12-09 14:15
> Try https://nightly.link/V-Sekai/godot/workflows/runner/vsk-ufbx?preview

ufbx is awesome. I tested 92 FBX files and ufbx can import them correctly, including FBX files containing actions. Next I will continue to test other fbx files and will contact you if I encounter problems.
Thank you for integrating ufbx into Godot, that's great, can't wait to use it.
Since ufbx has no other dependencies, is it possible to integrate ufbx into Godot 4.2?I think it will be a long time before Godot 4.3 is released.

**Comment by fire** [comment] 2023-12-09 14:36
The common way that happens is we test in 4.3 then it is cherry picked into 4.2

**Comment by lyuma** [comment] 2023-12-24 04:17
I am not able to reproduce the issue: this model imports cleanly in Godot 4.2.1 with latest FBX2glTF:
![image](https://github.com/godotengine/FBX2glTF/assets/39946030/ed4c9ad5-c519-4fc3-9796-46aaf1652794)

If you have double checked FBX2glTF is installed in editor settings, can you please share the output?

Alternatively, it would be helpful to have the output of FBX2glTF directly. Is it possible to put the model and the FBX2glTF.exe in the same directory, open it in a `cmd` command prompt and type:
`FBX2glTF -i SM_Envr_Road_Road_03.fbx -b -o SM_Envr_Road_Road_03.glb`

(on mac, linux or Git Bash, you will need to add a `./` at the beginning of the command line.)

```
C:\Users\Home\Downloads>FBX2glTF -i SM_Envr_Road_Road_03.fbx -b -o SM_Envr_Road_Road_03.glb
Warning: could not find a image file for texture: base_color_texture.
Warning: Couldn't open file , skipping file.
Wrote 2481 bytes of binary glTF to SM_Envr_Road_Road_03.glb.
```

I will close this as not reproducible until further information or output is provided.

**Closed by lyuma** 2023-12-24 04:17 UTC
Labels: bug

**Comment by dszhblx** [comment] 2023-12-27 03:53
![QQ截图20231227115303](https://github.com/godotengine/FBX2glTF/assets/8831593/ec691d27-8c7d-439f-88ae-c8de47c4aa74)
@lyuma
